baseurl: /_site
title: Certum ex inertis
subtitle: Content-centric blogging
author: Dimitri Semenovich
simple_search: http://google.com/search
description: Dimitri's blog
name: DS
markdown: Kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:short_year/:title
timezone: America/New_York
imageurl: "https://source.unsplash.com/category/nature/2600x500"
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/